openapi: 3.0.3
info:
  title: Customer API
  version: 1.0.0

servers:
  - url: "http://localhost:8080/api"
    description: "Development server"

tags:
  - name: "Customer"
    description: "API for reading customer information"

paths:
  /customers:
    get:
      tags:
        - "Customer"
      operationId: "getCustomers"
      summary: Get all customers
      responses:
        '200':
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'

components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
      required:
        - id
        - name
        - email
