openapi: 3.0.3
info:
  title: G2L Backend API Gateway
  version: 1.0.0

servers:
  - url: "http://localhost:8080/api"
    description: "Development server"

tags:
  - name: "Authentication"
    description: "API for user authentication"

paths:
  /auth/login:
    post:
      tags:
        - "Authentication"
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: Unauthorized

components:
  schemas:
    User:
      allOf:
        - $ref: 'referentiel.yml#/components/schemas/User'
    AuthenticationResponse:
      type: object
      properties:
        accessToken:
          type: string
      required:
        - accessToken
